-- CreateTable
CREATE TABLE "CURRENCY_CONVERTOR" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "symbol" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CURRENCY_CONVERTOR_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CURRENCY_CONVERTOR_name_key" ON "CURRENCY_CONVERTOR"("name");

-- CreateIndex
CREATE UNIQUE INDEX "CURRENCY_CONVERTOR_code_key" ON "CURRENCY_CONVERTOR"("code");
